sudo: required

services:
 - docker

env:
  matrix:
    - ARCH=arm
    - ARCH=arm64
    - ARCH=amd64

script:
  - ./travis-build.sh
  - ./travis-test.sh
  - >
    if [ -n "$TRAVIS_TAG" ]; then
      # push image
      ./travis-deploy.sh
    fi
